version: '3.8'

services:
  strongswan:
    image: strongswan-gmssl:5.9.6-ubuntu
    container_name: strongswan
    privileged: true
    network_mode: host
    
    volumes:
      - ./config/swanctl:/etc/swanctl
      - ./logs:/var/log
    
    environment:
      - TZ=Asia/Shanghai
    
    restart: unless-stopped
    
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
