connections {
    gmsm-server {
        version = 2
        # 国密算法优先，标准算法后备
        proposals = sm4-sm3-modp2048,aes256-sha256-modp2048
        
        local_addrs = 0.0.0.0
        
        local {
            auth = psk
            id = vpn-server@test.com
        }
        
        remote {
            auth = psk
            id = vpn-client@test.com
        }
        
        children {
            gmsm-tunnel {
                local_ts = 0.0.0.0/0
                remote_ts = dynamic
                
                # ESP 国密算法优先
                esp_proposals = sm4-sm3,aes256-sha256
                
                mode = tunnel
                dpd_action = clear
            }
        }
        
        pools = roadwarrior-pool
    }
}

pools {
    roadwarrior-pool {
        addrs = 10.10.10.0/24
        dns = 8.8.8.8, 114.114.114.114
    }
}

secrets {
    ike-gmsm {
        id-server = vpn-server@test.com
        id-client = vpn-client@test.com
        secret = "GmSM_VPN_Test_2025"
    }
}
