connections {
    gmsm-client {
        version = 2
        local_addrs = %any
        remote_addrs = 101.126.148.5
        
        # 国密算法优先，标准算法后备
        proposals = 1031-sm3-modp2048,aes256-sha256-modp2048
        
        local {
            auth = psk
            id = vpn-client@test.com
        }
        
        remote {
            auth = psk
            id = vpn-server@test.com
        }
        
        children {
            gmsm-tunnel {
                local_ts = 0.0.0.0/0
                remote_ts = 0.0.0.0/0
                
                # ESP 国密算法优先
                esp_proposals = 1031-sm3,aes256-sha256
                
                start_action = start
                close_action = restart
                dpd_action = restart
                mode = tunnel
            }
        }
        
        vips = 0.0.0.0
    }
}

secrets {
    ike-gmsm {
        id-client = vpn-client@test.com
        id-server = vpn-server@test.com
        secret = "GmSM_VPN_Test_2025"
    }
}
