connections {
    gmsm-client {
        version = 2
        # 先测试标准算法
        proposals = aes256-sha256-modp2048
        
        remote_addrs = 101.126.148.5
        
        local {
            auth = psk
            id = vpn-client@test.com
        }
        
        remote {
            auth = psk
            id = vpn-server@test.com
        }
        
        children {
            gmsm-tunnel {
                local_ts = 0.0.0.0/0
                remote_ts = 0.0.0.0/0
                
                # ESP 标准算法
                esp_proposals = aes256-sha256
                
                start_action = trap
                dpd_action = restart
                close_action = restart
            }
        }
    }
}

secrets {
    ike-gmsm {
        id-local = vpn-client@test.com
        id-remote = vpn-server@test.com
        secret = "GmSM_VPN_Test_2025"
    }
}
